### ISSUE TITLE
Security: Switch to audited secp256k1 implementation

### ISSUE THREAD

**Issue by paulmillr** [ecies/js#696]
https://github.com/paulmillr/noble-curves provide audited, fast, tree-shakeable, esm-compatible secp256k1 implementation.

Your current implementation seems to be using elliptic? Which is not actively maintained.

If you want users to use safe, audited code, then switch is the way.

**Comment by frankhinek** [comment]
I would second @paulmillr 's comments.

Block / [TBD](https://tbd.website/) is in need of a maintained and audited ECIES library and would welcome the opportunity to collaborate on updating this package to use @noble/curves.

**Comment by kigawas** [comment]
@frankhinek I updated to use @noble/curves.

@paulmillr Since I didn't find any util function for converting compressed/uncompressed format, I had to use a trick like

```ts
    this.uncompressed = Buffer.from(secp256k1.getSharedSecret(ONE, buffer, false));
    this.compressed = Buffer.from(secp256k1.getSharedSecret(ONE, buffer, true));
```

**Comment by paulmillr** [comment]
```js
const uncomp = secp256k1.getSharedSecret(ONE, buffer, false);
const comp = secp256k1.Point.fromHex(unc).toRawBytes(true);
```

**Comment by jcalfee** [comment]
[regarding](https://www.npmjs.com/package/@noble/post-quantum)

> [!IMPORTANT] NIST published IR 8547, prohibiting classical cryptography (RSA, DSA, ECDSA, ECDH) after 2035. Australian ASD does same thing after 2030. Take it into an account while designing a new cryptographic system.

Please forgive me if I got this all wrong, and I'm certainly not worthy of the title cryptographer.  Isn't NIST ran by the NSA, the same organization that spies on its own "citizens" and is implicated in controversy over their chosen elliptic curve parameters?  To be clear, I do not believe this implicates the curve used here secp256k1 (also used in bitcoin and most other blockchains).  I want to choose libraries wisely because we may be going in different directions here in the future esp. if what I suspect is happening is true: the NSA maybe advising against curves it does not control in the name of quantum resistance which, for all I know and by way reputation from the claimant, quantum resistance and derogatory use of the term "classical cryptography" could very well contain, to some degree, unfounded propaganda.

Again, I'm not proposing that there is any vulnerability here or in your library.  I'm proposing, as a non-expert, that this could become a conflict of interests if we don't consider such things.  It is a LONG game. And I'm always open to feedback; I only want the truth whatever it may be.

**Comment by paulmillr** [comment]
@jcalfee 

> I do not believe this implicates the curve used here secp256k1

Yes, it implicates secp256k1, p256, and every other elliptic curve. It implicates all of them. It's Shor's algorithm.

> the NSA maybe advising against curves it does not control in the name of quantum resistance

So just keep using secp256k1 and add falcon or slh-dsa to it. Use hybrids, problem solved.

**Comment by jcalfee** [comment]
Yes, I will stick with secp256k1, but nothing lasts forever.  I'm just puzzled why, in cryptography, the standards very high but yet this three letter agency seams to get a free pass.  Anyways, that is very interesting about Shor's algorithm; I'll keep my eyes on that. 
 Thanks!
